version: "3.8"
services:
  mongodb:
    image: mongo:4.2-bionic
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - /home/<user>/clearpay/database:/data/db
      - /home/<user>/clearpay/scripts:/data/scripts
    ports:
      - 27017:27017
    restart: unless-stopped

  clearpay-be:
    image: esanchezp/clearpay-be:latest
    container_name: clearpay-be
    ports:
      - 8080:8080
    restart: unless-stopped
    command: ["--spring.data.mongodb.host=localhost",
              "--spring.data.mongodb.port=27017",
              "--spring.data.mongodb.database=clearpay",
              "--spring.data.mongodb.username=clearpayAdmin",
              "--spring.data.mongodb.password=h6rU2xWjT@=StU+s"]
